### ISSUE TITLE
Handle 2 active keys on rotote

### ISSUE THREAD

**Issue by miketypeguy** [Signiant/LOCK#1]
When rotating a key that has 2 active keys the code should be able handle the exception and ask to delete one.  Right now it's failing on exception:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Volumes/secure/git/github/LOCK/project/main.py", line 158, in <module>
    main()
  File "/Volumes/secure/git/github/LOCK/project/main.py", line 108, in main
    rotate_update(configMap, user_data, username)
  File "/Volumes/secure/git/github/LOCK/project/main.py", line 154, in rotate_update
    method_to_call(configMap, username, **key_args)
  File "/Volumes/secure/git/github/LOCK/project/plugins/iam.py", line 117, in get_new_key
    new_key = create_key(client, username)
  File "/Volumes/secure/git/github/LOCK/project/plugins/iam.py", line 89, in create_key
    response = client.create_access_key(UserName=username)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.LimitExceededException: An error occurred (LimitExceeded) when calling the CreateAccessKey operation: Cannot exceed quota for AccessKeysPerUser: 2`

**Comment by miketypeguy** [comment]
Turns out this issue only happened if keys were created at the same time up to the minute
