### ISSUE TITLE
Error on validating keys due to typo.

### ISSUE THREAD

**Issue by miketypeguy** [Signiant/LOCK#2]
Getting the following:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Volumes/secure/git/github/LOCK/project/main.py", line 158, in <module>
    main()
  File "/Volumes/secure/git/github/LOCK/project/main.py", line 106, in main
    rotate_update(configMap, user_data, username)
  File "/Volumes/secure/git/github/LOCK/project/main.py", line 154, in rotate_update
    method_to_call(configMap, username, **key_args)
  File "/Volumes/secure/git/github/LOCK/project/plugins/iam.py", line 115, in get_new_key
    delete_older_key(configMap, username, client)
  File "/Volumes/secure/git/github/LOCK/project/plugins/iam.py", line 37, in delete_older_key
    delete_prompt(configMap, username, client, keyid1)
  File "/Volumes/secure/git/github/LOCK/project/plugins/iam.py", line 50, in delete_prompt
    choice = input('There are 2 keys. Delete the old access key: % ? (y/n) \n' % key)
ValueError: unsupported format character '?' (0x3f) at index 47`

Should just need to add an s to that %

**Comment by haggaret** [comment]
Thanks!
